spring.application.name=Docker

server.port=8080

#these settings are for postgresql database connection in my machine
# i have to change the configuration according to container configuration and not this machine
#because i want to connect to the container
# configuration that i used in docker-compose.yml file
spring.datasource.url=jdbc:postgresql://postgres:5432/absidb
spring.datasource.username=absi
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#there is also a way where u can use env variables in docker compose file in the app section
# where u connect which the db from there and also specify everything here also in Db section  and
# delete everything from here
#and dockerfile would be different also , it would contain commands as clean and creating(clean
# package ) the jar file and this way but we have to skip testing the connection to Db at the
# start of the app and this is the best way and we should not skip tests just for this project
